name: First Workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-22.04  # Available images can be found on https://github.com/actions/runner-images
    steps:
      - name: Print greeting
        run: echo "Hello"
      - name: Print goodbye
        run: echo "Done!, Bye"
