name: First Workflow
on: workflow_dispatch # when to run it

jobs:
  first_job:
    runs-on: ubuntu-22.04  # Available images can be found on https://github.com/actions/runner-images
    steps:
      - name: Print greeting
        run: echo "Hello"
      - name: Print goodbye
        run: echo "Done!, Bye"

# If you need to run multiple shell commands (or multi-line commands, 
# e.g., for readability), you can easily do so by adding the pipe symbol (|) as a value after the run: key.
#
# Like this:
# ...
# run: |
#     echo "First output"
#     echo "Second output"
#
# This will run both commands in one step.
