name: Second Action
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04 # This already has many pre-installed tools including Node.js, you can find them on https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v5 # Note that this is a GitHub-provided action: https://github.com/marketplace/actions/checkout, you can find other actions on the GitHub Marketplace.
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-22.04
    needs: test # Depends on test job
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."